name: Generate Contribution Graphs

on:
  schedule:
    - cron: "0 0 * * *" # jalan setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Pacman Contribution Graph
        uses: hediet/github-pacman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          outputPath: "./output/pacman.svg"

      - name: Push Generated Files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add output/pacman.svg
          git commit -m "Update Pacman contribution graph"
          git push
 
      - name: Generate Snake Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: luqmanaru
          outputs: |
            output/snake.svg
