name: Generate Contribution Graphs

on:
  schedule:
    - cron: "0 0 * * *" # jalan setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Generate Snake Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: luqmanaru
          outputs: |
            output/snake.svg
