name: Generate Contribution Graphs

on:
  schedule:
    - cron: "0 0 * * *" # jalan setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman Contribution Graph
        uses: hediet/github-pacman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        # menambahkan langkah untuk menyimpan output Pacman
      - name: Save Pacman Contribution Graph to Output
        run: mv pacman-contribution-graph.svg output/pacman-contribution-graph.svg
      
      - name: Generate Snake Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: luqmanaru
          outputs: |
            output/snake.svg
